FROM python:3.11 as compile-image
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

FROM python:3.11
COPY --from=compile-image /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /jobask_api

COPY ./ ./


EXPOSE 3030

ENTRYPOINT ["uvicorn", "server:app", "--reload", "--host", "0.0.0.0", "--port", "3030", "--access-log"]
#ENTRYPOINT ["ls"]
